import type { Recipe } from './types.js'

const recipe = {
    "name": "MangoHud",
    "launchOptions": [
        {
            "id": "mangohud",
            "group": "MangoHud",
            "name": "MangoHud",
            "on": "mangohud %command%",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "mangohud-config-preset-none",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "None",
            "fallbackValue": true,
        },
        {
            "id": "mangohud-config-preset-0",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=0\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "No Hud",
        },
        {
            "id": "mangohud-config-preset-1",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=1\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "FPS Only",
        },
        {
            "id": "mangohud-config-preset-2",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=2\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Horizontal",
        },
        {
            "id": "mangohud-config-preset-3",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=3\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Extended",
        },
        {
            "id": "mangohud-config-preset-4",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=4\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Detailed",
        },
        {
            "id": "mangohud-fps-limit-none",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "None",
            "fallbackValue": true,
        },
        {
            "id": "mangohud-fps-limit-30",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=30\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "30",
        },
        {
            "id": "mangohud-fps-limit-60",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=60\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "60",
        },
        {
            "id": "mangohud-fps-limit-72",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=72\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "72",
        },
        {
            "id": "mangohud-fps-limit-82",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=82\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "82",
        },
        {
            "id": "mangohud-fps-limit-90",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=90\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "90",
        },
        {
            "id": "mangohud-fps-limit-120",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=120\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "120",
        },
        {
            "id": "mangohud-fps-limit-144",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=144\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "144",
        },
        {
            "id": "mangohud-fps-limit-165",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=165\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "165",
        },
        {
            "id": "mangohud-fps-limit-180",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=180\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "180",
        },
        {
            "id": "mangohud-fps-limit-240",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=240\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "240",
        },
        {
            "id": "mangohud-fps-limit-360",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=360\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "360",
        },
        {
            "id": "mangohud-fps-limit-480",
            "group": "MangoHud",
            "name": "FPS Limit",
            "on": "MANGOHUD_CONFIG=\"fps_limit=480\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-fps-limit",
            "valueName": "480",
        },
    ],
} satisfies Recipe

export default recipe
