import type { Recipe } from './types.js'

const recipe = {
    "name": "MangoHud",
    "launchOptions": [
        {
            "id": "mangohud",
            "group": "MangoHud",
            "name": "MangoHud",
            "on": "mangohud %command%",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "mangohud-config-preset-none",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "None",
            "fallbackValue": true,
        },
        {
            "id": "mangohud-config-preset-0",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=0\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "No Hud",
        },
        {
            "id": "mangohud-config-preset-1",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=1\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "FPS Only",
        },
        {
            "id": "mangohud-config-preset-2",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=2\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Horizontal",
        },
        {
            "id": "mangohud-config-preset-3",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=3\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Extended",
        },
        {
            "id": "mangohud-config-preset-4",
            "group": "MangoHud",
            "name": "MangoHud Preset",
            "on": "MANGOHUD_CONFIG=\"preset=4\"",
            "off": "",
            "enableGlobally": false,
            "valueId": "mangohud-config-preset",
            "valueName": "Detailed",
        },
    ],
} satisfies Recipe

export default recipe
