import type { Recipe } from './types.js'

const recipe = {
    "name": "Proton",
    "launchOptions": [
        {
            "id": "proton-log",
            "group": "Proton",
            "name": "Proton Log",
            "on": "PROTON_LOG=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-wait-attach",
            "group": "Proton",
            "name": "Wait For Debugger",
            "on": "PROTON_WAIT_ATTACH=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-renderer-default",
            "group": "Proton",
            "name": "Proton Renderer",
            "on": "",
            "off": "",
            "enableGlobally": false,
            "valueId": "proton-renderer",
            "valueName": "Default",
            "fallbackValue": true,
        },
        {
            "id": "proton-renderer-wined3d",
            "group": "Proton",
            "name": "Proton Renderer",
            "on": "PROTON_USE_WINED3D=1",
            "off": "",
            "enableGlobally": false,
            "valueId": "proton-renderer",
            "valueName": "wined3d (OpenGL)",
        },
        {
            "id": "proton-disable-d3d11",
            "group": "Proton",
            "name": "Disable D3D11",
            "on": "PROTON_NO_D3D11=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-disable-d3d10",
            "group": "Proton",
            "name": "Disable D3D10",
            "on": "PROTON_NO_D3D10=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-dxvk-d3d8",
            "group": "Proton",
            "name": "DXVK D3D8",
            "on": "PROTON_DXVK_D3D8=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-no-esync",
            "group": "Proton",
            "name": "Disable Esync",
            "on": "PROTON_NO_ESYNC=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-no-fsync",
            "group": "Proton",
            "name": "Disable Fsync",
            "on": "PROTON_NO_FSYNC=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-disable-nvapi",
            "group": "Proton",
            "name": "Disable NVAPI",
            "on": "PROTON_DISABLE_NVAPI=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-hide-nvidia-gpu",
            "group": "Proton",
            "name": "Hide Nvidia GPU",
            "on": "PROTON_HIDE_NVIDIA_GPU=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-enable-wayland",
            "group": "Proton",
            "name": "Enable Wayland",
            "on": "PROTON_ENABLE_WAYLAND=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-enable-hdr",
            "group": "Proton",
            "name": "Enable HDR",
            "on": "PROTON_ENABLE_HDR=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-fsr4-upgrade",
            "group": "Proton",
            "name": "FSR 4 Upgrade",
            "on": "PROTON_FSR4_UPGRADE=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-heap-delay-free",
            "group": "Proton",
            "name": "Heap Delay Free",
            "on": "PROTON_HEAP_DELAY_FREE=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-old-gl-string",
            "group": "Proton",
            "name": "Old GL String",
            "on": "PROTON_OLD_GL_STRING=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-integer-scaling",
            "group": "Proton",
            "name": "Integer Scaling",
            "on": "WINE_FULLSCREEN_INTEGER_SCALING=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-set-game-drive",
            "group": "Proton",
            "name": "Set Game Drive",
            "on": "PROTON_SET_GAME_DRIVE=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-no-dxgi-device-manager",
            "group": "Proton",
            "name": "No DXGI Device Manager",
            "on": "WINE_DO_NOT_CREATE_DXGI_DEVICE_MANAGER=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-disable-vulkan-opwr",
            "group": "Proton",
            "name": "Disable Vulkan OPWR",
            "on": "WINE_DISABLE_VULKAN_OPWR=1",
            "off": "",
            "enableGlobally": false,
        },
        {
            "id": "proton-xalia-default",
            "group": "Proton",
            "name": "Xalia",
            "on": "",
            "off": "",
            "enableGlobally": false,
            "valueId": "proton-xalia",
            "valueName": "Default",
            "fallbackValue": true,
        },
        {
            "id": "proton-xalia-enable",
            "group": "Proton",
            "name": "Xalia",
            "on": "PROTON_USE_XALIA=1",
            "off": "",
            "enableGlobally": false,
            "valueId": "proton-xalia",
            "valueName": "Enable",
        },
        {
            "id": "proton-xalia-disable",
            "group": "Proton",
            "name": "Xalia",
            "on": "PROTON_USE_XALIA=0",
            "off": "",
            "enableGlobally": false,
            "valueId": "proton-xalia",
            "valueName": "Disable",
        },
    ],
} satisfies Recipe

export default recipe
